name: "NYC Trip Record S3 Deploy"
description: "S3 deploy with foldes structure"

inputs:
  environment:
    description: "Deploy environment"
    required: true
  aws-assume-role-arn:
    description: "OIDC role to assume"
    required: true
  aws-region:
    description: "AWS region"
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-assume-role-arn }}
        role-session-name: NycTripRecordOidcRole
        aws-region: ${{ inputs.aws-region }}
    
    - name: Terraform Init
      run: cd devops/terraform && terraform init
      shell: bash

    - name: Terraform Validate
      run: | 
        cd devops/terraform && terraform validate
      shell: bash

    - name: Terraform Plan
      id: terraform-plan
      run: |
        cd devops/terraform
        terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
        terraform plan \
        -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" \
        -out="${{ inputs.environment }}.plan"
      shell: bash
    
    - name: Terraform Apply
      id: terraform-apply
      run: | 
        cd devops/terraform
        terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
        terraform apply "${{ inputs.environment }}.plan"
      shell: bash
