name: "Databricks Setup"

on:
  workflow_dispatch:
    inputs:
      databricks_host:
        description: 'Seu host Databricks (obrigatório. Veja o README)'
        required: true
        type: string
      databricks_user_email:
        description: 'Seu email Databricks (obrigatório)'
        required: true
        type: string

permissions:
  id-token: write
  contents: read


jobs:
  databricks-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
          uses: actions/checkout@v4

      - uses: ./.github\actions\databricks_setup
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          databricks_host: ${{ github.event.inputs.databricks_host}}
          databricks_token: ${{ secrets.DATABRICKS_TOKEN }}
