name: "NYC Trip Record S3 Setup"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment do deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

env:
  SETUP_ENV: ${{ github.event.inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with: 
      environment: env.SETUP_ENV
      aws-region: ${{ vars.NYC_TRIP_RECORD_AWS_REGION }}
      aws-assume-role-arn: ${{ env.SETUP_ENV.secrets.NYC_TRIP_RECORD_OIDC_ARN }}
