name: "NYC Trip Record S3 Setup"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment do deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'


permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/terraform
        with: 
          environment: ${{ github.event.inputs.environment || 'dev' }}
          aws-assume-role-arn: ${{ vars.NYC_TRIP_RECORD_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.NYC_TRIP_RECORD_AWS_REGION }}
